## Development environment for Equal Experts test

---
- hosts: all
  tasks: 
  - name: Install ca-certificates
    ansible.builtin.apt:
      name: ca-certificates
      state: present
  - name: Install curl
    ansible.builtin.apt:
      name: curl
      state: present
  - name: Install gnupg
    ansible.builtin.apt:
      name: gnupg
      state: present
  - name: Install lsb-release
    ansible.builtin.apt:
      name: lsb-release
      state: present
  - name: Add Docker CE APT signing key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add Kubernetes APT signing key
    ansible.builtin.apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  - name: Add Docker CE repository
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: Add Kubernetes repository
    ansible.builtin.apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
  - name: Install Docker CE
    ansible.builtin.apt:
      name: docker-ce
      state: present
  - name: Install Docker CE CLI
    ansible.builtin.apt:
      name: docker-ce-cli
      state: present
  - name: Install ContainerD
    ansible.builtin.apt:
      name: containerd.io
      state: present
  - name: Enable and start Docker service
    ansible.builtin.service:
      name: docker
      enabled: yes
      state: started
  - name: Add ubuntu user to Docker group
    ansible.builtin.user:
      name: ubuntu
      groups: docker
      append: yes
  - name: Install Minikube
    ansible.builtin.apt:
      deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
  - name: Install kubectl
    ansible.builtin.apt:
      name: kubectl
      state: present
  - name: Install build-essential
    ansible.builtin.apt:
      name: build-essential
      state: present
